# Generated by Django 5.1.2 on 2024-10-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetwebapp', '0002_game_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
    ]
