# Generated by Django 5.1.2 on 2024-10-20 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesetwebapp', '0003_game_rate_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='games/'),
            preserve_default=False,
        ),
    ]
